
#Common config settings
[common]
	#Places backpack at place where player died
	backpackDeathPlace = true
	#Range: > 250
	tanksCapacity = 4000
	toolSlotsAcceptSwords = true
	disableCrafting = false
	#Backpack immune to any damage source (lava, fire), can't be destroyed, never disappears as floating item
	invulnerableBackpack = true
	#Places backpack at place where player died, replacing all blocks that are breakable and do not have inventory (backpackDeathPlace must be true in order to work)
	backpackForceDeathPlace = false
	enableBackpackAbilities = true
	#If true, backpack can only be worn by placing it in curios 'Back' slot
	#WARNING - Remember to TAKE OFF BACKPACK BEFORE enabling or disabling this integration!! - if not you'll lose your backpack
	curiosIntegration = false
	enableSleepingBagSpawnPoint = false
	#Enables wearing backpack directly from ground
	enableBackpackBlockWearable = true
	#Enables backpacks spawning in loot chests
	enableLoot = true

